//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNLTTH_BanSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.CTHoaDons = new HashSet<CTHoaDon>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> TonKho { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<System.DateTime> NgayXuatBan { get; set; }
        public string MaTacGia { get; set; }
        public string MaTheLoai { get; set; }
        public string AnhSach { get; set; }
        public string MaNhanVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDon> CTHoaDons { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
